### ISSUE TITLE
Is GitHub Pages necessary to deployment for this repo?

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/massaccess#22]
We are planning to switch from using subdirectories to subdomains for our organization-wide repos. Currently GitHub Pages is enabled and deploying to suffolklitlab.org/massaccess. Obviously that's not where the actual website lives (that's at courtformsonline.org).

Just wondering if the GitHub Pages deployment is necessary, and if so will I need to redirect suffolklitlab.org/massaccess to massaccess.suffolklitlab.org.

@nonprofittechy

**Comment by nonprofittechy** [comment]
@colarusso set this up

**Comment by nonprofittechy** [comment]
@colarusso set this up . Fwiw, this is the current court forms online.org repo, so it's definitely required. I don't recall if we're publishing the site this way though.

**Comment by samglover** [comment]
Yeah, I just wasn't sure if the GitHub Pages workflow is vestigial.

**Comment by colarusso** [comment]
Not published from here only a testing ground
